import type { Item } from '../../../../../../Types/item';

export const TSHIRT_MAP: Record<string, keyof Item> = {
  'Número': 'numero',
  'ID externo': 'idExterno',
  'Estado': 'estado',
  'Resumen': 'resumen',
  'Breve descripción': 'breveDescripcion',
  'Elemento de configuración': 'elementoConfiguracion',
  'Prioridad': 'prioridad',
  'Puntuación de riesgo': 'puntuacionRiesgo',
  'Grupo de asignación': 'grupoAsignacion',
  'Asignado a': 'asignadoA',
  'Creado': 'creado',
  'Actualizado': 'actualizado',
  'Sites': 'sites',
  'Vulnerability solution': 'vulnerabilitySolution',
  'Vulnerabilidad': 'vulnerabilidad',
  'Due date': 'dueDate',
};

export const SOUP_MAP: Record<string, keyof Item> = {
  'Tratada' : 'tratada',
  'Accion/Notas' : 'accionNotas',
  'Actualizacion estado' : 'actualizacionEstado',
  'Subida a produccion' : 'subidaProduccion',
  'Nombre Aplicación' : 'nombreAplicacion',
  'Application' : 'application',
  'Vulnerability ID' : 'vulnerabilityId',
  'Hostname' : 'hostname',
  'AB' : 'ab',
  'IT Development Area' : 'itDevelopmentArea',
  'COE' : 'coe',
  'State' : 'state',
  'State CSO' : 'stateCso',
  'Service' : 'service',
  'Origin' : 'origin',
  'Network' : 'network',
  'Type' : 'type',
  'Vulnerability Title' : 'vulnerabilityTitle',
  'Severity' : 'severity',
  'Domain' : 'domain',
  'Category ASVS' : 'categoryAsvs',
  'ASVS ID' : 'asvsId',
  'OWASP TOP 10' : 'owaspTop10',
  'PCI Status' : 'pciStatus',
  'Threat Description' : 'threatDescription',
  'Details' : 'details',
  'Target' : 'target',
  'Nº of Ocurrences' : 'numOcurrences',
  'Detection Date' : 'detectionDate',
  'New Code' : 'newCode',
  'Production Date' : 'productionDate',
  'Deadline' : 'deadline',
  'Days Open' : 'daysOpen',
  'Countermeasure' : 'countermeasure',
  'Environment' : 'environment',
  'References / CWE' : 'referencesCwe',
  'CVSS Base' : 'cvssBase',
  'CVSS Overall' : 'cvssOverall',
  'CVSS Rescored' : 'cvssRescored',
  'EPSS' : 'epss',
  'Easy of Exploit' : 'easyOfExploit',
  'CVSS Version' : 'cvssVersion',
  'CVSS Vector' : 'cvssVector',
  'Resolution Date' : 'resolutionDate',
  'ID Test' : 'idTest',
  'Deployed in production?' : 'deployedInProduction',
  'Duplicates?' : 'duplicates',
  'Detection team' : 'detectionTeam',
  'Observations' : 'observations',
  'IT Owner' : 'itOwner',
  'SW Provider' : 'swProvider',
  'VUL Code' : 'vulCode',
  'VIT Code' : 'vitCode',
  'AP' : 'ap',
  'Critical Case' : 'criticalCase',
  'Fecha comunicación SWF' : 'fechaComunicacionSwf',
  'HU Jira' : 'huJira',
  'Certificación pedida' : 'certificacionPedida',
  'Número Petición Certificacion' : 'numeroPeticionCertificacion',
  'Certificado' : 'certificado',
  'Fecha mitigacion' : 'fechaMitigacion',
  'Fecha certificación' : 'fechaCertificacion'
};